# .github/workflows/release.yml
name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажите вашу версию Python

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile app.py
        # Убираем shell: bash, чтобы использовать стандартный shell для каждой ОС

      - name: Rename Executable for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Rename-Item -Path dist\app.exe -NewName "IP Subnet Calculator.exe"

      - name: Rename Executable for macOS and Ubuntu
        if: runner.os != 'Windows'
        run: |
          mv dist/app "IP Subnet Calculator"
          chmod +x "IP Subnet Calculator"
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "IP_Subnet_Calculator-${{ matrix.os }}"
          path: |
            dist/IP Subnet Calculator.exe
            dist/IP Subnet Calculator

  upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-windows-latest"
          path: artifacts/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-macos-latest"
          path: artifacts/macos

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-ubuntu-latest"
          path: artifacts/ubuntu

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/dist/IP Subnet Calculator.exe
            artifacts/macos/dist/IP Subnet Calculator
            artifacts/ubuntu/dist/IP Subnet Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}