name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # Специальные зависимости для Ubuntu
      - name: Install Dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgirepository1.0-dev

      - name: Build Executable
        run: |
          pyinstaller --onefile app.py
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv dist/app.exe dist/IP_Subnet_Calculator.exe
          else
            mv dist/app dist/IP_Subnet_Calculator
            chmod +x dist/IP_Subnet_Calculator
          fi

      - name: List files in dist
        run: |
          echo "Artifacts for ${{ matrix.os }}:"
          ls -la dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-${{ matrix.os }}
          path: dist/IP_Subnet_Calculator.exe
        if: matrix.os == 'windows-latest'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-${{ matrix.os }}
          path: dist/IP_Subnet_Calculator
        if: matrix.os != 'windows-latest'

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-windows-latest
          path: artifacts/windows

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-ubuntu-latest
          path: artifacts/ubuntu

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-macos-latest
          path: artifacts/macos

      - name: List Downloaded Artifacts
        run: |
          echo "Windows Artifacts:"
          ls -la artifacts/windows
          echo "Ubuntu Artifacts:"
          ls -la artifacts/ubuntu
          echo "macOS Artifacts:"
          ls -la artifacts/macos

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          files: |
            artifacts/windows/IP_Subnet_Calculator.exe
            artifacts/ubuntu/IP_Subnet_Calculator
            artifacts/macos/IP_Subnet_Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
