name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable for Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile app.py
          mv dist/app.exe "dist/IP_Subnet_Calculator.exe"

      - name: Build Executable for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile app.py
          mv dist/app "dist/IP_Subnet_Calculator"
          chmod +x dist/IP_Subnet_Calculator

      - name: Upload Artifact for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-windows-latest
          path: dist/IP_Subnet_Calculator.exe

      - name: Upload Artifact for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-ubuntu-latest
          path: dist/IP_Subnet_Calculator