# .github/workflows/release.yml
name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажите вашу версию Python

      - name: Clean dist Directory
        run: |
          rm -rf dist/
        shell: bash

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile app.py

      - name: Rename Executable for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Rename-Item -Path dist\app.exe -NewName "IP_Subnet_Calculator.exe"

      - name: Rename Executable for macOS
        if: matrix.os == 'macos-latest'
        run: |
          mv dist/app "IP_Subnet_Calculator"
          chmod +x "IP_Subnet_Calculator"
        shell: bash

      - name: Rename Executable for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv dist/app "IP_Subnet_Calculator"
          chmod +x "IP_Subnet_Calculator"
        shell: bash

      - name: List dist Directory
        run: |
          echo "Listing contents of dist/:"
          ls -la dist/
        shell: bash

      - name: Upload Artifact for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: "IP_Subnet_Calculator-windows-latest"
          path: dist/IP_Subnet_Calculator.exe

      - name: Upload Artifact for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: "IP_Subnet_Calculator-macos-latest"
          path: dist/IP_Subnet_Calculator

      - name: Upload Artifact for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: "IP_Subnet_Calculator-ubuntu-latest"
          path: dist/IP_Subnet_Calculator

  upload-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-windows-latest"
          path: artifacts/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-macos-latest"
          path: artifacts/macos

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-ubuntu-latest"
          path: artifacts/ubuntu

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/IP_Subnet_Calculator.exe
            artifacts/macos/IP_Subnet_Calculator
            artifacts/ubuntu/IP_Subnet_Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
