name: Create Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # Специальные зависимости для Ubuntu
      - name: Install Dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libglib2.0-dev libgirepository1.0-dev

      - name: Build Executable with PyInstaller
        run: pyinstaller --onefile app.py
        shell: bash  # Используется для macOS и Ubuntu

      - name: List Dist Directory
        run: |
          if [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
            ls -la dist
          elif [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            Get-ChildItem dist
          fi

      - name: Rename Executable
        run: |
          if [[ "${{ matrix.os }}" == 'windows-latest' ]]; then
            mv dist/app.exe "dist/IP_Subnet_Calculator.exe"
          elif [[ "${{ matrix.os }}" == 'ubuntu-latest' ]]; then
            mv dist/app "dist/IP_Subnet_Calculator"
            chmod +x "dist/IP_Subnet_Calculator"
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "IP_Subnet_Calculator-${{ matrix.os }}"
          path: |
            dist/IP_Subnet_Calculator.exe
            dist/IP_Subnet_Calculator

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-windows-latest"
          path: artifacts/windows

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v3
        with:
          name: "IP_Subnet_Calculator-ubuntu-latest"
          path: artifacts/ubuntu

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/windows/IP_Subnet_Calculator.exe
            artifacts/ubuntu/IP_Subnet_Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}