name: Create Release

on:
  push:
    tags:
      - "v*.*.*"  # Триггер на пуш тегов вида v1.0.22

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      # Специальные зависимости для Ubuntu
      - name: Install Dependencies for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev libgirepository1.0-dev

      - name: Build Executable for Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          pyinstaller --onefile app.py
          Rename-Item -Path dist\app.exe -NewName IP_Subnet_Calculator.exe

      - name: Build Executable for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile app.py
          mv dist/app dist/IP_Subnet_Calculator
          chmod +x dist/IP_Subnet_Calculator

      - name: Build Executable for macOS
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile app.py
          mv dist/app dist/IP_Subnet_Calculator
          chmod +x dist/IP_Subnet_Calculator

      - name: List files in dist for Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Write-Output "Artifacts for Windows:"
          Get-ChildItem dist

      - name: List files in dist for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "Artifacts for Ubuntu:"
          ls -la dist

      - name: List files in dist for macOS
        if: matrix.os == 'macos-latest'
        run: |
          echo "Artifacts for macOS:"
          ls -la dist

      - name: Upload Artifact for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-windows-latest
          path: dist/IP_Subnet_Calculator.exe

      - name: Upload Artifact for Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-ubuntu-latest
          path: dist/IP_Subnet_Calculator

      - name: Upload Artifact for macOS
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: IP_Subnet_Calculator-macos-latest
          path: dist/IP_Subnet_Calculator

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-windows-latest
          path: artifacts/windows

      - name: Download Ubuntu Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-ubuntu-latest
          path: artifacts/ubuntu

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: IP_Subnet_Calculator-macos-latest
          path: artifacts/macos

      - name: List Downloaded Artifacts
        run: |
          echo "Windows Artifacts:"
          ls -la artifacts/windows
          echo "Ubuntu Artifacts:"
          ls -la artifacts/ubuntu
          echo "macOS Artifacts:"
          ls -la artifacts/macos

      - name: Upload Windows Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: artifacts/windows/IP_Subnet_Calculator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Ubuntu Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: artifacts/ubuntu/IP_Subnet_Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS Artifact to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: artifacts/macos/IP_Subnet_Calculator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
